boot.o: boot.S multiboot.h x86_desc.h types.h
context_switch.o: context_switch.S x86_desc.h types.h
handlers.o: handlers.S x86_desc.h types.h
paging_load.o: paging_load.S x86_desc.h types.h
syscall_handler.o: syscall_handler.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h types.h multiboot.h lib.h \
  x86_desc.h system_calls.h syscall_handler.h rtc.h keyboard.h paging.h \
  context_switch.h tss_switch.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h tests.h \
  idt.h handlers.h rtc.h keyboard.h syscall_handler.h system_calls.h \
  paging.h filesystem.h context_switch.h tss_switch.h pit.h
kernal.o: kernal.c
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h keyboard.h rtc.h paging.h filesystem.h system_calls.h \
  syscall_handler.h context_switch.h tss_switch.h terminal.h pit.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h system_calls.h \
  syscall_handler.h rtc.h paging.h filesystem.h x86_desc.h multiboot.h \
  context_switch.h tss_switch.h tests.h terminal.h pit.h
lib.o: lib.c lib.h types.h keyboard.h handlers.h system_calls.h \
  syscall_handler.h rtc.h paging.h filesystem.h x86_desc.h multiboot.h \
  context_switch.h tss_switch.h pit.h terminal.h
paging.o: paging.c x86_desc.h types.h lib.h paging.h
pit.o: pit.c pit.h lib.h types.h idt.h multiboot.h x86_desc.h i8259.h \
  debug.h tests.h system_calls.h syscall_handler.h rtc.h keyboard.h \
  paging.h filesystem.h context_switch.h tss_switch.h terminal.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h tests.h
schedule.o: schedule.c schedule.h types.h keyboard.h system_calls.h \
  syscall_handler.h rtc.h paging.h lib.h filesystem.h x86_desc.h \
  multiboot.h context_switch.h tss_switch.h
system_calls.o: system_calls.c system_calls.h syscall_handler.h rtc.h \
  types.h keyboard.h paging.h lib.h filesystem.h x86_desc.h multiboot.h \
  context_switch.h tss_switch.h terminal.h
terminal.o: terminal.c lib.h types.h keyboard.h handlers.h system_calls.h \
  syscall_handler.h rtc.h paging.h filesystem.h x86_desc.h multiboot.h \
  context_switch.h tss_switch.h terminal.h pit.h
tests.o: tests.c tests.h types.h x86_desc.h lib.h keyboard.h i8259.h \
  filesystem.h rtc.h
tss_switch.o: tss_switch.c tss_switch.h x86_desc.h types.h
